language: java
jdk:
  - openjdk8

branches:
  only:
    - main #오직 main 브랜치에서 push 될때만

# Travis CI 서버의 Home
#Gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포때부터 다시 받지 않도록 설정합니다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


#master 브랜치에 PUSH 되었을때 수행하는 명령어입니다.
#여기선 프로젝트 내부에 둔 gradlew을 통해 clean & build 를 수행합니다

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - qkrtprjs456@gmail.com